env: "local" # local, dev, prod
storage_path: "./storage/storage.db"
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s
  user: "myuser"
  password: "mypass"
clients:
  sso:
    address: "localhost:44044"
    timeout: 5s
    retries_count: 3
app_secret: "url-secret"
app_id: 5
